language: objective-c
osx_image: xcode61
before_install:
    - git submodule update --init --recursive
script:
    - xcodebuild -project External/CocoaHTTPServer/Framework/CocoaHTTPServer/CocoaHTTPServer.xcodeproj -scheme 'CocoaHTTPServer' -sdk macosx -arch x86_64 test CODE_SIGNING_REQUIRED=NO
    - xcodebuild -project Framework/RoutingHTTPServer/RoutingHTTPServer.xcodeproj -scheme 'RoutingHTTPServer' -sdk macosx -arch x86_64 build CODE_SIGNING_REQUIRED=NO
    - xcodebuild -project Framework/RoutingHTTPServer/RoutingHTTPServer.xcodeproj -scheme 'RoutingHTTPServer' -sdk iphonesimulator -arch i386 build CODE_SIGNING_REQUIRED=NO